services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ${PWD}/
        target: /app/data/final
    command: poetry run python main.py