services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ${PWD}/
        target: /harbour/environment
      
    ports:
      - "1488:1488"
